"""empty message

Revision ID: 1b2481e24ed4
Revises:
Create Date: 2024-12-13 23:31:08.259928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2481e24ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('xp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('xp')
        batch_op.drop_column('level')
    # ### end Alembic commands ###
