"""add page iterations and watcher verdicts

Revision ID: 87a3a2ef6f65
Revises: 1b2481e24ed4
Create Date: 2026-04-07 08:37:37.253440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a3a2ef6f65'
down_revision = '1b2481e24ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_iteration_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('current_iteration_id')

    # ### end Alembic commands ###
